Repository AmiruthaVallii/climate-monitor, pull requests merged in 2025-08, with the labels that each got.

#39 Created an architecture diagram for the project
  documentation/architecture-diagram.png
Labels: documentation

#101 Created new Lambda IAM role
  terraform/main.tf
Labels: bug

#112 Basic login page for dashboard complete
  dashboard/.streamlit/favicon.png
  dashboard/hello.txt
  dashboard/login.py
  dashboard/requirements.txt
Labels: dashboard

#109 56 ETL Orchestrator lambda for historical/future data
  orchestrator-new-location/dockerfile
  orchestrator-new-location/new_location_orchestrator.py
  orchestrator-new-location/requirements.txt
Labels: ETL

#114 Created scheduler for live weather and air quality readings
  terraform/main.tf
Labels: system component

#142 Created homepage
  dashboard/homepage.py
  dashboard/modules/nav.py
  dashboard/pages/air_quality.py
  dashboard/pages/floods.py
  dashboard/pages/login.py
  dashboard/pages/profile.py
  dashboard/pages/weather.py
Labels: dashboard

#157 Terraform for notifications ECR done
  terraform/main.tf
Labels: system component

#154 added readme with all files described
  README.md
Labels: documentation

#166 Terraform config for notifications lambda done
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#164 Created dockerfile for notifications
  notifications/dockerfile
  notifications/requirements.txt
Labels: enhancement

#167 Added architecture diagram
  documentation/architecture-diagram.png
Labels: documentation

#171 reduced amount of data loaded and cached
  dashboard/pages/weather.py
Labels: dashboard

#175 Gave email lambdas the required permissions
  terraform/main.tf
Labels: bug

#183 Final update to arch diagram
  documentation/architecture-diagram.png
Labels: documentation

#189 Gave invoke lambda permission to dashboard
  terraform/main.tf
Labels: bug
